from app import db
from datetime import datetime


class Supplier(db.Model):
    """
    Supplier (vendor) profiles.
    NOTE: When WhatsApp integration is enabled, whatsapp_number will be used
    via Twilio API for automated procurement notifications.
    """
    __tablename__ = 'suppliers'

    id               = db.Column(db.Integer, primary_key=True)
    name             = db.Column(db.String(200), nullable=False)
    contact_person   = db.Column(db.String(150), nullable=True)
    email            = db.Column(db.String(200), nullable=True)
    phone            = db.Column(db.String(30), nullable=True)
    whatsapp_number  = db.Column(db.String(30), nullable=True)   # Format: +201XXXXXXXXX
    address          = db.Column(db.Text, nullable=True)
    rating           = db.Column(db.Float, default=3.0)         # 1-5 stars
    lead_time_days   = db.Column(db.Integer, default=7)         # Avg delivery days
    is_active        = db.Column(db.Boolean, default=True)
    notes            = db.Column(db.Text, nullable=True)
    created_at       = db.Column(db.DateTime, default=datetime.utcnow)

    procurement_requests = db.relationship('ProcurementRequest', back_populates='supplier', lazy='dynamic')

    @property
    def total_orders(self):
        return self.procurement_requests.count()

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'contact_person': self.contact_person,
            'email': self.email,
            'phone': self.phone,
            'whatsapp_number': self.whatsapp_number,
            'address': self.address,
            'rating': self.rating,
            'lead_time_days': self.lead_time_days,
            'is_active': self.is_active,
            'notes': self.notes,
            'total_orders': self.total_orders,
            'created_at': self.created_at.isoformat(),
        }


class ProcurementRequest(db.Model):
    """
    Purchase orders / restock requests sent to suppliers.
    NOTE: When Shopify integration is enabled, auto-create procurement requests
    when Shopify reports low inventory webhooks.
    """
    __tablename__ = 'procurement_requests'

    STATUS_CHOICES = ['Draft', 'Sent', 'Confirmed', 'Received', 'Cancelled']

    id               = db.Column(db.Integer, primary_key=True)
    supplier_id      = db.Column(db.Integer, db.ForeignKey('suppliers.id'), nullable=False)
    product_id       = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=False)
    quantity         = db.Column(db.Integer, nullable=False)
    unit_cost        = db.Column(db.Float, nullable=True)
    total_cost       = db.Column(db.Float, nullable=True)
    status           = db.Column(db.String(30), default='Draft')
    is_auto_suggested = db.Column(db.Boolean, default=False)  # True = generated by analytics
    notes            = db.Column(db.Text, nullable=True)
    requested_at     = db.Column(db.DateTime, default=datetime.utcnow)
    expected_at      = db.Column(db.DateTime, nullable=True)
    received_at      = db.Column(db.DateTime, nullable=True)

    supplier = db.relationship('Supplier', back_populates='procurement_requests')
    product  = db.relationship('Product')

    def to_dict(self):
        return {
            'id': self.id,
            'supplier_id': self.supplier_id,
            'supplier_name': self.supplier.name if self.supplier else None,
            'product_id': self.product_id,
            'product_name': self.product.name if self.product else None,
            'product_sku': self.product.sku if self.product else None,
            'quantity': self.quantity,
            'unit_cost': self.unit_cost,
            'total_cost': self.total_cost,
            'status': self.status,
            'is_auto_suggested': self.is_auto_suggested,
            'notes': self.notes,
            'requested_at': self.requested_at.isoformat(),
            'expected_at': self.expected_at.isoformat() if self.expected_at else None,
            'received_at': self.received_at.isoformat() if self.received_at else None,
        }
